



<!-- start featured research inc -->



<!-- gray line -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr>

   <td bgcolor="#bbbbbb"><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

<tr>

   <td><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

</table>



<!-- featured research articles -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td colspan="3" width="356" height="20" bgcolor="#ADB5C6"><a href="javascript:openAllLatestResearch()" class="sectionHead">&nbsp;Featured Research</a></td>

   <td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>



<% if (clientAccess) { %>

<tr>

   <td width="356" height="1" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>

<% } else { %>

<tr>

   <td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>

<tr>

   <td width="356" height="25" colspan="3" bgcolor="#FFFFFF"><a href="/pages/story.php.id.8849.s.8.jsp"><img src="/images/homepage/images_100/buy_research.gif" width="356" height="22" alt="" border="0"></a></td>

</tr>

<%} %>







<!-- text with summary -->

<tr>

   <td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="/research/spotlight/asset_53069.jsp" class="largeBlueLink">IT Offshore Outsourcing</a><br>

<span class="smallGrayText">Find out about the implications on your organization, your business and your people.</span><br></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>









<!-- text -->

<tr>

   <td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:void(null)" onclick="openResult('DisplayDocument?id=417794')" class="smallBlueLink">Five Steps to Comply With Your Software Licenses</a></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>







<!-- text -->

<tr>

   <td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:void(null)" onclick="openResult('DisplayDocument?id=417690')" class="smallBlueLink">Consumers Will Reshape CRM Marketing</a></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>









<!-- text -->

<tr>

   <td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="/pages/story.php.id.8813.s.8.jsp" class="smallBlueLink">Oracle's Bid for PeopleSoft &#151; The Latest Analysis</a></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>





<% if (clientAccess) { %>

<!-- monthly research review -->

<tr>

   <td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="/1_researchanalysis/mrr/mrr.jsp" class="smallBlueLink">Monthly Research Review</a></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>

<%} %>





<!-- more latest reasearch -->

<tr>

   <td width="356" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="16" alt="" border="0"></td>

</tr>

<tr> 

   <td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/gray_arrow.gif" width="10" height="10" vspace="2" alt="" border="0"></td>

   <td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:openAllLatestResearch()" class="smallGreenLink">The latest Gartner Research</a></td>

   <td width="6" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>

<tr>

   <td width="356" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="11" alt="" border="0"></td>

</tr>

</table>

<!-- end featured research articles -->

<!-- end featured research inc -->
