
$hash{'20050615INFORMATION SECURITY: STATE OF THE PRACTICEMILAN'} = "f";
$hash{'20050614INFORMATION SECURITY: STATE OF THE PRACTICEBRUSSELS'} = "e";
$hash{'20050607THE FUTURE OF IT (AND ITS BUSINESS CONSEQUENCES)ZAGREB'} = "d";
$hash{'20050520SEMICONDUCTORS THROUGH 2010: THE NEXT GROWTH CYCLELONDON'} = "c";
$hash{'20050511SERVICE ORIENTED ARCHITECTURE: INSTRUCTIONS FOR USEAMSTERDAM'} = "b";
$hash{'20050510IT SERVICES IN EUROPE: TRENDS AND DIRECTIONSCOPENHAGEN'} = "a";

foreach $key (sort { $a cmp $b } keys %hash) {

    print "$key $hash{$key}\n";

}
