

<!--  start mq_vr inc -->

<!-- begin magic quadrant and vendor rating section -->



<script src="/pages/docs/gartner/hc/scripts/utils.js"></script>

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" height="2" bgcolor="#BBBBBB"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr>

</table>



<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="10"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

   <td width="336"><img src="/images/trans_pixel.gif" width="336" height="1" alt="" border="0"></td>

   <td width="10"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

   <td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>



<!-- mq's -->

<tr> 

  <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

   <td width="336" height="2" bgcolor="#F5F5F5"><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

<a href="/mq/asset_50486.jsp"><img src="/images/homepage/images_100/mquadrants_logo.gif" width="175" height="21" border="0" alt=""></a>

   <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

    <span class="smallGrayText">Scopri quali fornitori sono leader, "visionari", "sfidanti", <br />di nicchia<br></span>

    <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

    <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/mq/asset_50486.jsp" class="smallThinBlueLink">Altri Magic Quadrants</a><br>

   <div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

   </td>

   <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>

<tr> 

  <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

  <td width="336" height="2" bgcolor="#E3E9EC">

  <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

  <span class="focusAreaLink"><b>Ultimo Magic Quadrant:&nbsp;&nbsp;</b></span>

<div><img src="/images/trans_pixel.gif" width="20" height="12" alt="" border="0"><a href="javascript:void(null)" onclick="popUpQuadrant(118651)" class="smallThinBlueLink"><b>E-Mail Active-Archiving Products<img src="/images/trans_pixel.gif" width="1" height="12" alt="" border="0"></b></a></div>

 <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>

  <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>



<!-- hc's -->

<tr>   

   <td colspan="3" width="356" height="2"><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

<tr> 

  <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

  <td width="336" height="2" bgcolor="#F5F5F5"><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

   <a href="/hc/asset_50595.jsp"><img src="/images/homepage/images_100/hypecycles_logo.gif" width="130" height="21" border="0" alt=""></a>

   <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

   <span class="smallGrayText">Gartner Hype Cycles illustra con chiarezza la differenza tra le aspettative non realistiche e il futuro della tecnologia.<br></span>

<div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

  <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/hc/asset_50595.jsp" class="smallThinBlueLink">Altri Hype Cycles</a><br>

   <div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

   </td>

   <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>

<tr> 

  <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

  <td width="336" height="2" bgcolor="#E3E9EC">

  <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

  <span class="focusAreaLink"><b>Ultimo Hype Cycle:&nbsp;</b></span>

  <a href="javascript:void(null)" onclick="popUpHypeCycle(117446)" class="smallThinBlueLink"><b>Business Activity Monitoring</b></a><br><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

   </td>

   <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>



<!-- vendor ratings -->

<tr>

  <td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>

<tr> 

  <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

  <td width="336" height="2" bgcolor="#F5F5F5"><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

  <a href="/1_researchanalysis/vendor_rating/vr_main.html"><img src="/images/homepage/images_100/vendorratings_logo.gif" width="125" height="21" border="0" alt=""></a>

  <div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div>

  <span class="smallGrayText">Le ultime valutazioni Gartner sui principali fornitori.<br></span>

  <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

  <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/1_researchanalysis/vendor_rating/vr_main.html" class="smallThinBlueLink">Altri Vendor Ratings</a><br>

   <div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

  </td>

  <td width="10" height="2" bgcolor="#F5F5F5"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>

<tr> 

  <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

  <td width="336" height="2" bgcolor="#E3E9EC" valign="top">

   <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

      <table width="336">

      <tr> 

          <td width="130" valign="top">

          <span class="focusAreaLink"><b>Ultime valutazioni: </b></span>

          </td>

          <td width="206" valign="top">



          <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/1_researchanalysis/vendor_rating/vr_bearingpoint.jsp" class="smallThinBlueLink"><b>Bearing Point</b></a><br>



           <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/1_researchanalysis/vendor_rating/vr_deutsche.jsp" class="smallThinBlueLink"><b>Deutsche Telekom</b></a><br>



           <img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" alt="" border="0"><a href="/1_researchanalysis/vendor_rating/vr_motorola.jsp" class="smallThinBlueLink"><b>Motorola</b></a><br>



      <div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div>

          </td>

       </tr>  

      </table>

      



   </td>

   <td width="10" height="2" bgcolor="#E3E9EC"><img src="/images/trans_pixel.gif" width="10" height="2" alt="" border="0"></td>

</tr>

<tr>

   <td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>

</table>

	

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" height="2" bgcolor="#BBBBBB"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr>

</table>

   

   

<!-- whiteline -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr>

   <td bgcolor="#ffffff"><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

</table> 



  

<!-- Gartner Weblogs -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="356" height="20" bgcolor="#ADB5C6"><a href="http://weblog.gartner.com/weblog/weblogIndex.php" class="sectionHead">&nbsp;Gartner Weblogs</a></td>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>

</table>



<table width="360" border="0" cellspacing="0" cellpadding="0">





<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><span class="smallGrayText">Find out what Gartner analysts are thinking about current business & technology issues &#133;<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

         </td>

      </tr>

      

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr> 







<!-- Unconventional Thinking -->

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><a href="http://fellows.blog.gartner.com/weblog/index.php?blogid=2" class="smallBlueLink">Unconventional Thinking</a><br>

         <span class="smallGrayText">Gartner's leading analysts discuss new approaches and new ideas.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="3" alt="" border="0"></div>

         </td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="4" height="16" alt="" border="0" align="left"><img src="/images/arrowBlue.gif" width="13" height="8" alt="" hspace="0" vspace="2" border="0" align="left"><a href="http://fellows.blog.gartner.com/weblog/index.php?blogid=2" class="smallThinBlueLink">Latest Topic:

      <img src="/images/trans_pixel.gif" width="13" height="1" alt="" hspace="0" vspace="0" border="0" align="left">Still More About Opting In or Out</a><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div></td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

   </table>

   </td>

</tr>







<!-- Sarbanes-Oxley Act -->

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><a href="http://sox.weblog.gartner.com/weblog/index.php?blogid=11" class="smallBlueLink">Sarbanes-Oxley Act</a><br>

         <span class="smallGrayText">The U.S. Sarbanes-Oxley Act has changed the rules of business. Learn how this will affect your IS organization.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="3" alt="" border="0"></div>

         </td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="4" height="16" alt="" border="0" align="left"><img src="/images/arrowBlue.gif" width="13" height="8" alt="" hspace="0" vspace="2" border="0" align="left"><a href="http://sox.weblog.gartner.com/weblog/index.php?blogid=11" class="smallThinBlueLink">Latest Topic: 

      <img src="/images/trans_pixel.gif" width="13" height="1" alt="" hspace="0" vspace="0" border="0" align="left">Roles and Responsibility</a><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div></td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

   </table>

   </td>

</tr>







<!-- outsourcing -->

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><a href="http://outsourcing.weblog.gartner.com/weblog/index.php?blogid=9" class="smallBlueLink">Outsourcing</a><br>

         <span class="smallGrayText">Separate the myths from the reality about outsourcing and share best practices.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="3" alt="" border="0"></div>

         </td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="4" height="16" alt="" border="0" align="left"><img src="/images/arrowBlue.gif" width="13" height="8" alt="" hspace="0" vspace="2" border="0" align="left"><a href="http://outsourcing.weblog.gartner.com/weblog/index.php?blogid=9" class="smallThinBlueLink">Latest Topic:<br>

      <img src="/images/trans_pixel.gif" width="13" height="1" alt="" hspace="0" vspace="0" border="0" align="left">Business Process Outsourcing Chicken and Egg</a><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div></td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr> 





<!-- Does IT matter -->

<tr> 

   <td width="340" bgcolor="#FFFFFF" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></td>

         <td><a href="http://itmatters.weblog.gartner.com/weblog/index.php?blogid=10" class="smallBlueLink">Does IT Matter?</a><br>

         <span class="smallGrayText">Join the discussion about the future of IT and how it will affect your business.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="3" alt="" border="0"></div>

         </td>

      </tr>

      

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="4" height="16" alt="" border="0" align="left"><img src="/images/arrowBlue.gif" width="13" height="8" alt="" hspace="0" vspace="2" border="0" align="left"><a href="http://itmatters.weblog.gartner.com/weblog/index.php?blogid=10" class="smallThinBlueLink">Latest Topic:<br> <img src="/images/trans_pixel.gif" width="13" height="1" alt="" hspace="0" vspace="0" border="0" align="left">Make IT An Enabler, Not An Inhibitor, to Change</a><div><img src="/images/trans_pixel.gif" width="1" height="8" alt="" border="0"></div></td>

      </tr>

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr>



<tr>

   <td width="356" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr> 

</table>





<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="28" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/trans_pixel.gif" width="4" height="1" alt="" border="0"><img src="/images/homepage/gray_arrow.gif" width="10" height="10" vspace="2" hspace="0" alt="" border="0"></td>

   <td width="330" valign="top" bgcolor="#FFFFFF"><a href="http://weblog.gartner.com/weblog/weblogIndex.php" class="smallGreenLink">View All Gartner Weblogs</a><div><img src="/images/trans_pixel.gif" width="318" height="10" alt="" border="0"></div></td>

</tr>

</table>

<!-- End Gartner Weblogs -->



	

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" height="2" bgcolor="#BBBBBB"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr>

</table>





























   

   

<!-- whiteline -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr>

   <td bgcolor="#ffffff"><img src="/images/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

</table> 



  

<!-- Start Research Collections -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="356" height="20" bgcolor="#ADB5C6"><a href="/pages/story.php.id.3021.s.8.jsp" class="sectionHead">&nbsp;Research Collections</a></td>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>

<tr>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="356" height="5" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="5" alt="" border="0"></td>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>



</table>



<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><span class="headFootGrayBold">Get research articles, tools and other resources.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

         </td>

      </tr>

      

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr> 











<!-- Outsourcing -->

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><a href="/pages/section.php.id.2215.s.8.jsp" class="smallBlueLink">Outsourcing</a><br>

         <span class="smallGrayText">Find out how to choose the right vendors and negotiate the best deals.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

         </td>

      </tr>

      

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr> 















<!-- The Business Value of IT -->

<tr> 

   <td width="340" bgcolor="#FFFFff" valign="top" colspan="2">

   <div><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></div>

      <table border="0" cellspacing="0" cellpadding="0">

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><a href="http://bvit.gartner.com/section.php.id.2132.s.13.jsp" class="smallBlueLink" target="_blank">The Business Value of IT</a><br>

         <span class="smallGrayText">Learn why IT investments succeed or fail &#151; and what it really takes to determine value.<br></span>

         <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div>

         </td>

      </tr>

      

      <tr>

         <td width="10" height="1"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

         <td><img src="/images/trans_pixel.gif" width="330" height="1" alt="" border="0" class="dottedLine"><div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0"></div></td>

      </tr>

      </table>

   </td>

</tr> 









<tr>

   <td width="356" colspan="3" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr> 

</table>





<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="28" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/trans_pixel.gif" width="4" height="1" alt="" border="0"><img src="/images/homepage/gray_arrow.gif" width="10" height="10" vspace="2" hspace="0" alt="" border="0"></td>

   <td width="330" valign="top" bgcolor="#FFFFFF"><a href="/pages/story.php.id.3021.s.8.jsp" class="smallGreenLink">View All Research Collections</a><div><img src="/images/trans_pixel.gif" width="318" height="10" alt="" border="0"></div></td>

</tr>

</table>

<!-- End Research Collections -->



	





<% if (clientAccess) { %>

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" height="2" bgcolor="#ffffff"><img src="/images/trans_pixel.gif" width="360" height="10" alt="" border="0"></td>

</tr>

</table>

<% } else { %>



	

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" height="2" bgcolor="#BBBBBB"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr>

<tr> 

   <td width="360" height="2" bgcolor="#ffffff"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr>

</table>



  

<!-- Start Gartner Executive Reports -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="356" height="20" bgcolor="#ADB5C6"><a href="/5_about/news/exec_reports.jsp" class="sectionHead">&nbsp;Gartner Executive Reports</a></td>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>

<tr>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

   <td width="356" height="5" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="356" height="12" alt="" border="0"></td>

   <td width="2" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>

</table>



<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr>

   <td width="10"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>

   <td width="130" valign="top"><a href="/5_about/news/exec_reports.jsp" class="smallGreenLink"><img src="/images/homepage/images_100/erbooks100x60.gif" width="100" height="60" alt="" border="0" align="top"></a></td>

   <td valign="top"><span class="smallGrayText">Five comprehensive reports about CRM, Web Services, Security, Outsourcing and Asset Management.<br></span>

   <div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>

   <td width="20"><img src="/images/trans_pixel.gif" width="20" height="1" alt="" border="0"></td>

</tr>

<tr>

   <td width="360" colspan="4" bgcolor="#FFFFFF"><img src="/images/trans_pixel.gif" width="360" height="2" alt="" border="0"></td>

</tr> 

</table>



<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="28" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/trans_pixel.gif" width="4" height="1" alt="" border="0"><img src="/images/homepage/gray_arrow.gif" width="10" height="10" vspace="2" hspace="0" alt="" border="0"></td>

   <td width="330" valign="top" bgcolor="#FFFFFF"><a href="/5_about/news/exec_reports.jsp" class="smallGreenLink">View All Executive Reports</a><div><img src="/images/trans_pixel.gif" width="318" height="10" alt="" border="0"></div></td>

</tr>

</table>





<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

   <td width="360" bgcolor="#ffffff"><img src="/images/trans_pixel.gif" width="360" height="12" alt="" border="0"></td>

</tr>

</table>

<% } %>

<!--  end mq_vr inc -->

</table>

