<style>
.FAGrayBold {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-weight:bold; color: #666666; text-decoration: none}
</style>

<!-- start focus area inc -->
<table width="200" border="0" cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="196" height="2"><img src="/images/trans_pixel.gif" width="196" height="2" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
</tr>
<tr>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
<td width="196" height="33"><img src="/images/homepage/FA_home196.gif" width="196" height="40" alt="Focus Areas" border="0"></td>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
</tr>
</table>


<table width="200" border="0" cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="186" height="2"><img src="/images/trans_pixel.gif" width="186" height="2" alt="" border="0"></td>
<td bgcolor="#ffffff" width="10" valign="top"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
</tr>
<tr>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
<td bgcolor="#f5f5f5" width="186" valign="top">
    <table width="186" border="0" cellspacing="0" cellpadding="0">
   <tr>
   <td width="16" height="2"><img src="/images/trans_pixel.gif" width="10" height="4" hspace="3" vspace="0" alt="" border="0"></td>
   <td width="170" height="2" valign="top"><img src="/images/trans_pixel.gif" width="166" hspace="0" vspace="0" height="2" alt="" border="0"></td>
   </tr>
   <tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48248.jsp" class="FAGrayBold">Application Development</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48249.jsp" class="FAGrayBold">Application Integration <br>& Middleware</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48250.jsp" class="FAGrayBold">Business Intelligence <br>& Data Warehousing</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48251.jsp" class="FAGrayBold">Client Platforms</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48252.jsp" class="FAGrayBold">Communications Services</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48253.jsp" class="FAGrayBold">CRM</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48254.jsp" class="FAGrayBold">Digital Documents <br>& Imaging</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48255.jsp" class="FAGrayBold">Emerging Technologies</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48256.jsp" class="FAGrayBold">Enterprise Management</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48257.jsp" class="FAGrayBold">Enterprise Networking <br>& Equipment</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48258.jsp" class="FAGrayBold">ERP & Supply Chain Management</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
<td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48259.jsp" class="FAGrayBold">Financial Services</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48260.jsp" class="FAGrayBold">Government</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48261.jsp" class="FAGrayBold">Healthcare</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_4862.jsp" class="FAGrayBold">Higher Education</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48584.jsp" class="FAGrayBold">IT Management</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48263.jsp" class="FAGrayBold">IT Services & Outsourcing</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48264.jsp" class="FAGrayBold">Knowledge Support</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48265.jsp" class="FAGrayBold">Mobile &amp; Wireless</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48583.jsp" class="FAGrayBold">Open Source Software</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48266.jsp" class="FAGrayBold">Public Network Infrastructure Equipment</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48267.jsp" class="FAGrayBold">Security & Privacy</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48268.jsp" class="FAGrayBold">Semiconductors</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48269.jsp" class="FAGrayBold">Servers & Storage</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48270.jsp" class="FAGrayBold">Small & Midsize Business</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48271.jsp" class="FAGrayBold">Technology & Society</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>
<tr>
   <td width="16" valign="top"><img src="/images/homepage/arrow_trans_k.gif" width="10" height="10" hspace="3" vspace="0" alt="" border="0" align="top"></td>
   <td width="170" valign="top"><a href="/research/focus_areas/asset_48272.jsp" class="FAGrayBold">Web Services</a><div><img src="/images/trans_pixel.gif" width="1" height="6" alt="" border="0"></div></td>
</tr>

<tr>
   <td width="16" valign="top"><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></td>
   <td width="170" valign="top"><img src="/images/trans_pixel.gif" width="1" height="4" alt="" border="0"></td>
</tr>

   </table>
</td>
<td bgcolor="#f5f5f5" width="10" valign="top"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0" hspace="0" vspace="0"></td>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
</tr>
<tr>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="186" height="2"><img src="/images/trans_pixel.gif" width="186" height="2" alt="" border="0"></td>
<td bgcolor="#ffffff" width="10" valign="top"><img src="/images/trans_pixel.gif" width="10" height="1" alt="" border="0"></td>
<td bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
</tr>
</table>



<table width="200" border="0" cellspacing="0" cellpadding="0">
<tr>
   <td bgcolor="#CECECE"><img src="/images/trans_pixel.gif" width="200" height="2" alt="" border="0"></td>
</tr>

</table>

<!-- Start Membership Programs -->
<table width="200" border="0" cellspacing="0" cellpadding="0">
	<tr>
 		<td rowspan="20" bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
 		<td bgcolor="#FFFFFF" width="196" height="2"><img src="/images/trans_pixel.gif" width="196" height="2" alt="" border="0"></td>
 		<td rowspan="20" bgcolor="#FFFFFF" width="2"><img src="/images/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>
	</tr>

   <tr>
      <td width="196" height="25"><img src="/images/homepage/membership_pro196.gif" width="196" height="25" alt="Membership Programs" border="0"></td>
   </tr>




<tr>
   <td bgcolor="#FFFFFF" width="196" height="2"><img src="/images/trans_pixel.gif" width="196" height="2" alt="" border="0"></td>
</tr>
   <script><!--
   function jumper2(newLoc) {
   	newPage=newLoc.options[newLoc.selectedIndex].value
   	if (newPage!="") { window.open(newPage,"_self")}
   	newLoc.selectedIndex=0 }

   browserName = navigator.appName;
   browserVersion = parseInt(navigator.appVersion);

   if (browserName == "Netscape" && browserVersion == 4)
   {
   document.write('<tr><td bgcolor="#ADB3B9">');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="3" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2126.s.8.jsp" class="membershipProgramLink">Architects &#38; Planners</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/story.php.id.3451.s.19.jsp" class="membershipProgramLink">Chief Information Officers</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2192.s.8.jsp" class="membershipProgramLink">CRM Managers</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2123.s.8.jsp" class="membershipProgramLink">Investment Professionals</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2211.s.8.jsp" class="membershipProgramLink">IT Operations Directors</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2183.s.8.jsp" class="membershipProgramLink">IT Security Directors</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2217.s.8.jsp" class="membershipProgramLink">IT Sourcing &#38; Procurement <br>&nbsp;&nbsp;&nbsp;&nbsp;Directors</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2125.s.8.jsp" class="membershipProgramLink">Network &#38; Telecom Managers</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2214.s.8.jsp" class="membershipProgramLink">Service Line Management</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div><img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="http://www3.gartner.com//pages/section.php.id.2213.s.8.jsp" class="membershipProgramLink">Telecom Product Management</a>');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="4" alt="" border="0"></div>');
   document.write('</td></tr>');
   	}

   else
   	{

   document.write('<tr>');
   document.write('<td bgcolor="#ADB3B9"><span class="mainRightNavLink">');
   document.write('<div><img src="/images/trans_pixel.gif" width="196" height="5" alt="" border="0"></div>');
   document.write('<img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0" align="left" hspace="2">Get the insight, services and<div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0" align="left" hspace="2">tools you need to succeed in</div><img src="/images/trans_pixel.gif" width="1" height="1" alt="" border="0" align="left" hspace="2">your job<div><img src="/images/trans_pixel.gif" width="1" height="12" alt="" border="0" align="left"></div></span>');
   document.write('</tr>');
   document.write('<tr>');
   document.write('<form>');
   document.write('<td bgcolor="#ADB3B9" valign="top"><img src="/images/trans_pixel.gif" width="1" height="1" border="0" align="left">');
   document.write('<select name="newloc" onchange="jumper2(this.form.newloc);"  STYLE="width:184px;height:22px;font-family:Arial,Helvetica,verdana,sans-serif;font-size:11px;background:#EFEFEF;">');
   document.write('<option selected>Choose Your Job Role</option>');
   document.write('<option value="/pages/section.php.id.2126.s.8.jsp"> Architects &#38; Planners</option>');
   document.write('<option value="/pages/story.php.id.3451.s.19.jsp"> Chief Information Officers</option>');
   document.write('<option value="/pages/section.php.id.2192.s.8.jsp"> CRM Managers</option>');
   document.write('<option value="/pages/section.php.id.2123.s.8.jsp"> Investment Professionals</option>');
   document.write('<option value="/pages/section.php.id.2211.s.8.jsp"> IT Operations Directors</option>');
   document.write('<option value="/pages/section.php.id.2183.s.8.jsp"> IT Security Directors</option>');
   document.write('<option value="/pages/section.php.id.2217.s.8.jsp"> IT Sourcing &#38; Procurement Directors</option>');
   document.write('<option value="/pages/section.php.id.2125.s.8.jsp"> Network &#38; Telecom Managers</option>');
   document.write('<option value="/pages/section.php.id.2214.s.8.jsp"> Service Line Management</option>');
   document.write('<option value="/pages/section.php.id.2213.s.8.jsp"> Telecom Product Management</option>');
   document.write('<option value=""> </option>');
   document.write('</select>');
   document.write('<div><img src="/images/trans_pixel.gif" width="186" height="14" alt="" border="0"></div>');
   document.write('</td>');
   document.write('</form>');
   document.write('</tr>');
}
   // -->
   </script>
      <NOSCRIPT>
<tr>
   <td bgcolor="#ADB3B9">
   <div><img src="/images/trans_pixel.gif" width="196" height="3" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2126.s.8.jsp" class="membershipProgramLink">Architects &#38; Planners</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/story.php.id.3451.s.19.jsp" class="membershipProgramLink">Chief Information Officers</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2192.s.8.jsp" class="membershipProgramLink">CRM Managers</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2123.s.8.jsp" class="membershipProgramLink">Investment Professionals</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2211.s.8.jsp" class="membershipProgramLink">IT Operations Directors</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2183.s.8.jsp" class="membershipProgramLink">IT Security Directors</a>
      <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2217.s.8.jsp" class="membershipProgramLink">IT Sourcing &#38; Procurement <br>&nbsp;&nbsp;Directors</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2125.s.8.jsp" class="membershipProgramLink">Network &#38; Telecom Managers</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="/pages/section.php.id.2214.s.8.jsp" class="membershipProgramLink">Service Line Management</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="1" alt="" border="0"></div>
   <img src="/images/homepage/trans_arrow.gif" width="8" height="8" alt="" hspace="3" border="0"><a href="http://www3.gartner.com//pages/section.php.id.2213.s.8.jsp" class="membershipProgramLink">Telecom Product Management</a>
   <div><img src="/images/trans_pixel.gif" width="196" height="4" alt="" border="0"></div>
   </td>
</tr>
   </NOSCRIPT>
</table>

<!-- End Membership Programs -->

<table width="200" border="0" cellspacing="0" cellpadding="0">
<tr>
   <td bgcolor="#FFFFFF" colspan="3"><img src="/images/trans_pixel.gif" width="200" height="2" alt="" border="0"></td>
</tr>
<tr>
   <td bgcolor="#CECECE" colspan="3"><img src="/images/trans_pixel.gif" width="200" height="2" alt="" border="0"></td>
</tr>
<tr>
   <td bgcolor="#FFFFFF" colspan="3"><img src="/images/trans_pixel.gif" width="200" height="2" alt="" border="0"></td>
</tr>
</table>

<!-- end focus area inc -->
