



<!-- Oracle promo -->



<map name="oracle">

<area shape="rect" coords="0, 0, 344, 40" href="/pages/story.php.id.8813.s.8.jsp">

<area shape="rect" coords="0, 40, 160, 75" href="/pages/story.php.id.8813.s.8.jsp">

<area shape="rect" coords="164, 42, 344, 75" href="/teleconferences/asset_47094.jsp">

</map>

<!-- end Oracle promo -->







<!--  -->





<!-- gray line -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr>

<td bgcolor="#bbbbbb"><img src="./img/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

<tr>

<td><img src="./img/trans_pixel.gif" width="1" height="2" alt="" border="0"></td>

</tr>

</table>





<!-- featured research articles -->

<table width="360" border="0" cellspacing="0" cellpadding="0">

<tr> 

<td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

<td colspan="3" width="356" height="20" bgcolor="#ADB5C6"><a href="javascript:openAllLatestResearch()" class="sectionHead">&nbsp;Featured Research</a></td>

<td rowspan="100" width="2" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="2" height="1" alt="" border="0"></td>

</tr>



<% if (clientAccess) { %>

<tr>

<td width="356" height="1" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>



<% } else { %>

<tr>

<td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>

<tr>

<td width="356" height="25" colspan="3" bgcolor="#FFFFFF"><a href="/pages/story.php.id.8849.s.8.jsp"><img src="/images/homepage/promo_02/buy_research.gif" width="356" height="22" alt="" border="0"></a></td>

</tr>

<%} %>





<!-- image -->

<tr>

<td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="6" alt="" border="0"></td>

</tr>

<tr> 

<td width="350" bgcolor="#FFFFFF" valign="top" colspan="2"><a href="/pages/story.php.id.9407.s.8.jsp"><img src="/images/homepage/promo_02/6407b_ett_homepage.jpg" width="100" height="60" hspace="6" vspace="3" align="left" alt="IT Professional" border="0"></a>

<table border="0" cellspacing="0" cellpadding="0">

<tr>

<td><a href="/pages/story.php.id.9407.s.8.jsp" class="largeBlueLink">Semiconductors &#151; <br>The Next Big Thing</a><br>

<span class="smallGrayText">Gartner takes a look at the future of the semiconductor market.</span><br>

</td>

</tr>

</table>

</td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="3" height="1" alt="" border="0"></td>

</tr>

<tr>

<td width="356" height="2" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="2" alt="" border="0"></td>

</tr>







<!-- text -->

<tr>

<td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

<td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

<td width="328" valign="top" bgcolor="#FFFFFF"><a href="/research/asset_47924.jsp" class="smallBlueLink">Worm & Virus Outbreak</a></td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>









<!-- text -->

<tr>

<td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

<td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

<td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:void(null)" onclick="openResult('DisplayDocument?id=408290')" class="smallBlueLink">The Difference Between E-mail Marketing <br>and Spam</a></td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>







<!-- text -->

<tr>

<td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

<td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

<td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:void(null)" onclick="openResult('DisplayDocument?id=408461')" class="smallBlueLink">PC Disposal</a></td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>









<% if (clientAccess) { %>



<!-- monthly research review -->

<tr>

<td width="356" height="8" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="8" alt="" border="0"></td>

</tr>

<tr> 

<td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/reversed_blue_arrow.gif" width="9" height="9" vspace="2" alt="" border="0"></td>

<td width="328" valign="top" bgcolor="#FFFFFF"><a href="/1_researchanalysis/mrr/mrr.jsp" class="smallBlueLink">Monthly Research Review</a></td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>



<%} %>





<!-- oracle bid for peoplesoft -->

<tr>

<td colspan="3"><img src="./img/trans_pixel.gif" width="1" height="10" alt="" border="0"></td>

</tr>

<tr>

<td colspan="3" align="center"><img src="/images/homepage/promo_02/oracle_replay_available.gif" width="344" height="75" alt="Oracle's Bid for PeopleSoft" border="0" usemap="#oracle">

</td>

</tr>



<!-- end oracle bid for peoplesoft -->



<!-- more latest reasearch -->

<tr>

<td width="356" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="6" alt="" border="0"></td>

</tr>

<tr> 

<td width="22" bgcolor="#FFFFFF" valign="top" align="center"><img src="/images/homepage/gray_arrow.gif" width="10" height="10" vspace="2" alt="" border="0"></td>

<td width="328" valign="top" bgcolor="#FFFFFF"><a href="javascript:openAllLatestResearch()" class="smallGreenLink">The latest Gartner Research</a></td>

<td width="6" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="6" height="1" alt="" border="0"></td>

</tr>

<tr>

<td width="356" colspan="3" bgcolor="#FFFFFF"><img src="./img/trans_pixel.gif" width="356" height="11" alt="" border="0"></td>

</tr>

<!-- end featured research articles -->
